#!/usr/bin/python
import re
import sys

NGINX_CONF_FILE = 'config/nginx.conf'
BIGMAX_CONF_FILE = 'config/bigmax.ini'
MAX_SETTINGS_FILE = '.max_settings'
SUPERVISOR_FILE = 'parts/supervisor/supervisord.conf'

# Do we have to enable ssl ?
enable = sys.argv[1].lower() == 'true'

if enable:
    # Enable NGINX SSL
    nginx = open(NGINX_CONF_FILE).read()
    subst = re.sub(r'#SSL#', '', nginx)
    open(NGINX_CONF_FILE, 'w').write(subst)

    # Enable MAX SSL parameters
    try:
        maxx = open(BIGMAX_CONF_FILE).read()
        subst = re.sub(r'\n\s*max\.(talk|server).*?\n', '\n', maxx)
        subst = re.sub(r'#SSL#', '', subst)
        open(BIGMAX_CONF_FILE, 'w').write(subst)
    except:
        print "No MAX part enabled"

    # Enable MAXSETTINGS SSL parameters
    try:
        maxsettings = open(MAX_SETTINGS_FILE).read()
        subst = re.sub(r'"maxserver":\s*"http://(.*?):\d+"', r'"maxserver": "https://\1"',  maxsettings)
        open(MAX_SETTINGS_FILE, 'w').write(subst)
    except:
        print "No maxsettings enabled"

    # Enable MAXSETTINGS SSL parameters
    try:
        supervisor = open(SUPERVISOR_FILE).read()
        supervisor = re.sub(r'\[program:max\]\s*\n*\s*command\s*=\s*(.*?)\n', r'[program:max]\ncommand = \1 --user pyramid\n',  supervisor)
        supervisor = re.sub(r'\[program:bigmax\]\s*\n*\s*command\s*=\s*(.*?)\n', r'[program:bigmax]\ncommand = \1 --user pyramid\n',  supervisor)
        supervisor = re.sub(r'\[program:maxtalk\]\s*\n*\s*command\s*=\s*(.*?)\n', r'[program:maxtalk]\ncommand = \1 --user pyramid\n',  supervisor)

        open(SUPERVISOR_FILE, 'w').write(supervisor)
    except:
        print "No supervisor found"

    print ' ** SSL Enabled **'
    print ' ** Change file ownership to pyramid and restart supervisor as root **'
